name: lint-and-build

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  validate-and-test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agentforge-web
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: agentforge-web/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build JS
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker Build
        uses: docker/build-push-action@v5
        with:
          context: ./agentforge-web
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max